#!/bin/bash
python main_eval.py --lam 20.0 --tao 3.0 --ifweight 1 > look4
python main_eval.py --lam 20.0 --tao 2.0 --ifweight 1 > look6
python main_eval.py --lam 20.0 --tao 4.0 --ifweight 1 > look7
python main_eval.py --lam 0.0 --tao 3.0 --ifweight 1 > look5
python main_eval.py --lam 0.0 --tao 3.0 --ifweight 0 > look3
